repos:
  # General formatting hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
        exclude: \.dart$
      - id: check-merge-conflict

  # Python (Django backend)
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1
    hooks:
      - id: isort
        files: ^backend/

  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black
        language_version: python3
        files: ^backend/

  - repo: https://github.com/PyCQA/flake8
    rev: 7.2.0
    hooks:
      - id: flake8
        additional_dependencies: [ flake8-django ]
        files: ^backend/

  - repo: local
    hooks:
      - id: check-migrations
        name: Check for missing Django migrations
        entry: backend/venv/Scripts/python.exe backend/manage.py makemigrations --check --dry-run
        language: system
        types: [ python ]
        pass_filenames: false

  # JavaScript/React (web-app)
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        files: ^web_app/.*\.(js|jsx|ts|tsx|css|scss|html|json|md)$

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v9.23.0
    hooks:
      - id: eslint
        files: ^web_app/
        args: [ "--config=web_app/eslint.config.cjs" ]

  # Flutter (mobile-app)
  - repo: local
    hooks:
      - id: dart-format
        name: Dart Format
        entry: dart format mobile_app/
        language: system
        pass_filenames: false

      - id: dart-analyze
        name: Dart Analyze
        entry: dart analyze
        language: system
        pass_filenames: false
