version: '3.8'

services:
  backend:
    build: ./backend
    environment:
      # Use the RDS endpoint and credentials
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_HOST=${DB_HOST}
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app

  frontend:
    build: ./web_app
    environment:
      - REACT_APP_API_URL=${REACT_APP_API_URL}
    ports:
      - "3000:3000"
    volumes:
      - ./web_app:/app
    depends_on:
      - backend
