# Generated by Django 5.1.6 on 2025-03-27 01:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_currentitem_orderitems'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='business_address',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='business_name',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='phone',
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='manager', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='restaurant',
            name='managers',
            field=models.ManyToManyField(related_name='restaurants', to='app.manager'),
        ),
    ]
