# Generated by Django 5.1.6 on 2025-03-27 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_item_stock'),
        ('app', '0005_remove_customuser_business_address_and_more'),
    ]

    operations = [
    ]
