# Generated by Django 5.1.7 on 2025-03-28 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_merge_20250327_1854'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='base64_image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
