# Generated by Django 5.1.7 on 2025-03-28 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_item_base64_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='restaurant_image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
