# Generated by Django 5.1.6 on 2025-04-09 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_ingredient'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='unwanted_ingredients',
            field=models.ManyToManyField(blank=True, related_name='excluded_from_order_items', to='app.ingredient'),
        ),
    ]
