# Generated by Django 5.1.6 on 2025-04-10 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_orderitem_unwanted_ingredients'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='estimated_pickup_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
