# Generated by Django 5.1.6 on 2025-04-17 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_orderitem_unwanted_ingredients'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='times_ordered',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
