# Generated by Django 5.1.6 on 2025-04-17 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_order_worker_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='beverage_eta_minutes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='estimated_beverage_ready_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='estimated_food_ready_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='food_eta_minutes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
