# Generated by Django 5.2 on 2025-04-22 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_order_beverage_eta_minutes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='fcm_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
