# Generated by Django 5.2 on 2025-04-23 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_customer_fcm_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='times_ordered',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
