# Generated by Django 5.2 on 2025-04-29 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_item_times_ordered'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='completion_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
