# Generated by Django 5.1.6 on 2025-04-30 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_item_times_ordered'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='base64_image',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='restaurant_image',
        ),
        migrations.AddField(
            model_name='item',
            name='item_image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='restaurant_image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
