# Generated by Django 5.2 on 2025-04-30 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_item_times_ordered'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='beverage_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('picked_up', 'Picked Up')], default='pending', max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='food_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('picked_up', 'Picked Up')], default='pending', max_length=50),
        ),
    ]
