# Generated by Django 5.2 on 2025-05-02 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_order_beverage_status_order_food_status'),
        ('app', '0019_remove_item_base64_image_and_more'),
    ]

    operations = [
    ]
