# Generated by Django 5.2 on 2025-05-02 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_order_completion_time_alter_order_start_time'),
        ('app', '0020_merge_20250502_0305'),
    ]

    operations = [
    ]
