# Generated by Django 5.1.6 on 2025-05-02 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_merge_20250502_0305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='beverage_eta_minutes',
        ),
        migrations.RemoveField(
            model_name='order',
            name='food_eta_minutes',
        ),
    ]
