# Generated by Django 5.2 on 2025-05-05 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_merge_20250502_2111'),
        ('app', '0021_promotionnotification'),
    ]

    operations = [
    ]
