# Generated by Django 5.1.6 on 2025-05-05 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_remove_order_beverage_eta_minutes_and_more'),
        ('app', '0022_merge_20250505_1436'),
    ]

    operations = [
    ]
