name: test-mobile

on:
  pull_request:
    branches:
      - main

  # push:
  #   branches:
  #     - ${{ github.head_ref || github.ref_name }}

jobs:
  test:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - uses: futureware-tech/simulator-action@v3
        with:
          model: 'iPhone 14'

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.3'
          channel: 'stable'

      - run: flutter pub get
      - run: flutter test