name: test-mobile

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - run: ls -R
        working-directory: sep2025-project-team_001/mobile_app

      - uses: futureware-tech/simulator-action@v3
        with:
          model: 'iPhone 15'

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.3'
          channel: 'stable'

      - run: flutter pub get
        working-directory: sep2025-project-team_001/mobile_app

      - run: flutter test
        working-directory: sep2025-project-team_001/mobile_app